CREATE TABLE SYSTEM.EAD_CAD_PRODUTOS (
	PROD_ID NUMBER,
	PROD_NOME VARCHAR2(50),
	PROD_VALOR NUMBER(22,0),
	PROD_STATUS CHAR(1) DEFAULT 'A' ,
	PROD_DT_INCL DATE,
	PROD_CAD_USER VARCHAR2(20),
	PROD_COD_ID VARCHAR2(22),
	CONSTRAINT EAD_CAD_PRODUTOS_PK PRIMARY KEY (PROD_ID),
	CONSTRAINT SYS_C007134 CHECK (PROD_ID),
	CONSTRAINT SYS_C007135 CHECK (PROD_NOME),
	CONSTRAINT SYS_C007136 CHECK (PROD_VALOR),
	CONSTRAINT SYS_C007137 CHECK (PROD_STATUS),
	CONSTRAINT SYS_C007138 CHECK (PROD_DT_INCL),
	CONSTRAINT SYS_C007139 CHECK (PROD_CAD_USER),
	CONSTRAINT SYS_C007141 CHECK (PROD_COD_ID)
) ;
CREATE UNIQUE INDEX EAD_CAD_PRODUTOS_PK ON SYSTEM.EAD_CAD_PRODUTOS (PROD_ID) ;


CREATE TABLE SYSTEM.EAD_CAD_USER (
	USU_ID NUMBER,
	USU_EMAIL VARCHAR2(100),
	USU_SENHA VARCHAR2(50),
	USU_NOME VARCHAR2(100),
	USU_LOGIN VARCHAR2(20),
	USU_TELEFONE VARCHAR2(20),
	CONSTRAINT EAD_CAD_USER_PK PRIMARY KEY (USU_ID),
	CONSTRAINT SYS_C006997 CHECK (USU_ID),
	CONSTRAINT SYS_C006998 CHECK (USU_EMAIL),
	CONSTRAINT SYS_C006999 CHECK (USU_SENHA),
	CONSTRAINT SYS_C007000 CHECK (USU_NOME),
	CONSTRAINT SYS_C007002 CHECK (USU_LOGIN),
	CONSTRAINT SYS_C007003 CHECK (USU_TELEFONE)
) ;
CREATE UNIQUE INDEX EAD_CAD_USER_PK ON SYSTEM.EAD_CAD_USER (USU_ID) ;
